INSERT INTO Cities VALUES ('Backa Topola', 101)
INSERT INTO Cities VALUES ('Mali Iđos', 101)
INSERT INTO Cities VALUES ('Subotica', 101)
INSERT INTO Cities VALUES ('Žitiste', 101)
INSERT INTO Cities VALUES ('Zrenjanin', 101)
INSERT INTO Cities VALUES ('Nova Crnja', 101)
INSERT INTO Cities VALUES ('Novi Bečej', 101)
INSERT INTO Cities VALUES ('Sečanj', 101)
INSERT INTO Cities VALUES ('Ada', 101)
INSERT INTO Cities VALUES ('Kanjiža', 101)
INSERT INTO Cities VALUES ('Kikinda', 101)
INSERT INTO Cities VALUES ('Novi Kneževac', 101)
INSERT INTO Cities VALUES ('Senta', 101)
INSERT INTO Cities VALUES ('Čoka', 101)
INSERT INTO Cities VALUES ('Alibunar', 101)
INSERT INTO Cities VALUES ('Bela Crkva', 101)
INSERT INTO Cities VALUES ('Vršac', 101)
INSERT INTO Cities VALUES ('Kovačica', 101)
INSERT INTO Cities VALUES ('Kovin', 101)
INSERT INTO Cities VALUES ('Opovo', 101)
INSERT INTO Cities VALUES ('Pančevo', 101)
INSERT INTO Cities VALUES ('Plandište', 101)
INSERT INTO Cities VALUES ('Apatin', 101)
INSERT INTO Cities VALUES ('Kula', 101)
INSERT INTO Cities VALUES ('Odžaci', 101)
INSERT INTO Cities VALUES ('Sombor', 101)
INSERT INTO Cities VALUES ('Bač', 101)
INSERT INTO Cities VALUES ('Bačka Palanka', 101)
INSERT INTO Cities VALUES ('Bački Petrovac', 101)
INSERT INTO Cities VALUES ('Beočin', 101)
INSERT INTO Cities VALUES ('Bečej', 101)
INSERT INTO Cities VALUES ('Vrbas', 101)
INSERT INTO Cities VALUES ('Žabalj', 101)
INSERT INTO Cities VALUES ('Srbobran', 101)
INSERT INTO Cities VALUES ('Sremski Karlovci', 101)
INSERT INTO Cities VALUES ('Temerin', 101)
INSERT INTO Cities VALUES ('Titel', 101)
INSERT INTO Cities VALUES ('Novi Sad', 101)
INSERT INTO Cities VALUES ('Inđija', 101)
INSERT INTO Cities VALUES ('Irig', 101)
INSERT INTO Cities VALUES ('Pećinci', 101)
INSERT INTO Cities VALUES ('Ruma', 101)
INSERT INTO Cities VALUES ('Sremska Mitrovica', 101)
INSERT INTO Cities VALUES ('Stara Pazova', 101)
INSERT INTO Cities VALUES ('Šid', 101)
INSERT INTO Cities VALUES ('Bogatić', 101)
INSERT INTO Cities VALUES ('Vladimirci', 101)
INSERT INTO Cities VALUES ('Koceljva', 101)
INSERT INTO Cities VALUES ('Kruptanj', 101)
INSERT INTO Cities VALUES ('Loznica', 101)
INSERT INTO Cities VALUES ('Ljubovija', 101)
INSERT INTO Cities VALUES ('Mali Zvornik', 101)
INSERT INTO Cities VALUES ('Šabac', 101)
INSERT INTO Cities VALUES ('Valjevo', 101)
INSERT INTO Cities VALUES ('Lajkovac', 101)
INSERT INTO Cities VALUES ('Ljig', 101)
INSERT INTO Cities VALUES ('Mionica', 101)
INSERT INTO Cities VALUES ('Ocečina', 101)
INSERT INTO Cities VALUES ('Ub', 101)
INSERT INTO Cities VALUES ('Velika Plana', 101)
INSERT INTO Cities VALUES ('Smederevo', 101)
INSERT INTO Cities VALUES ('Smederevska Palanka', 101)
INSERT INTO Cities VALUES ('Veliko Gradište', 101)
INSERT INTO Cities VALUES ('Golubac', 101)
INSERT INTO Cities VALUES ('Žabari', 101)
INSERT INTO Cities VALUES ('Žagubica', 101)
INSERT INTO Cities VALUES ('Kučevo', 101)
INSERT INTO Cities VALUES ('Malo Cniće', 101)
INSERT INTO Cities VALUES ('Petrovac', 101)
INSERT INTO Cities VALUES ('Požarevac', 101)
INSERT INTO Cities VALUES ('Aranđelovac', 101)
INSERT INTO Cities VALUES ('Batočina', 101)
INSERT INTO Cities VALUES ('Knić', 101)
INSERT INTO Cities VALUES ('Lapovo', 101)
INSERT INTO Cities VALUES ('Rača', 101)
INSERT INTO Cities VALUES ('Topola', 101)
INSERT INTO Cities VALUES ('Kragujevac', 101)
INSERT INTO Cities VALUES ('Despotovac', 101)
INSERT INTO Cities VALUES ('Jagodina', 101)
INSERT INTO Cities VALUES ('Paraćin', 101)
INSERT INTO Cities VALUES ('Rekovac', 101)
INSERT INTO Cities VALUES ('Svilajnac', 101)
INSERT INTO Cities VALUES ('Župrija', 101)
INSERT INTO Cities VALUES ('Bor', 101)
INSERT INTO Cities VALUES ('Kladovo', 101)
INSERT INTO Cities VALUES ('Majdanpek', 101)
INSERT INTO Cities VALUES ('Negotin', 101)
INSERT INTO Cities VALUES ('Boljevac', 101)
INSERT INTO Cities VALUES ('Zaječar', 101)
INSERT INTO Cities VALUES ('Knjaževac', 101)
INSERT INTO Cities VALUES ('Sokobanja', 101)
INSERT INTO Cities VALUES ('Belgrade', 101)
INSERT INTO Cities VALUES ('Arilje', 101)
INSERT INTO Cities VALUES ('Bajina Bašta', 101)
INSERT INTO Cities VALUES ('Kosjerić', 101)
INSERT INTO Cities VALUES ('Nova Varoš', 101)
INSERT INTO Cities VALUES ('Požega', 101)
INSERT INTO Cities VALUES ('Priboj', 101)
INSERT INTO Cities VALUES ('Prijepolje', 101)
INSERT INTO Cities VALUES ('Sjenica', 101)
INSERT INTO Cities VALUES ('Užice', 101)
INSERT INTO Cities VALUES ('Čajetina', 101)
INSERT INTO Cities VALUES ('Gornji Milanovac', 101)
INSERT INTO Cities VALUES ('Ivanjica', 101)
INSERT INTO Cities VALUES ('Lučani', 101)
INSERT INTO Cities VALUES ('Čačak', 101)
INSERT INTO Cities VALUES ('Vrnjačka Banja', 101)
INSERT INTO Cities VALUES ('Kraljevo', 101)
INSERT INTO Cities VALUES ('Novi Pazar', 101)
INSERT INTO Cities VALUES ('Raška', 101)
INSERT INTO Cities VALUES ('Tutin', 101)
INSERT INTO Cities VALUES ('Aleksandrovac', 101)
INSERT INTO Cities VALUES ('Brus', 101)
INSERT INTO Cities VALUES ('Varvarin', 101)
INSERT INTO Cities VALUES ('Kruševac', 101)
INSERT INTO Cities VALUES ('Trstenik', 101)
INSERT INTO Cities VALUES ('Ćićevac', 101)
INSERT INTO Cities VALUES ('Aleksinac', 101)
INSERT INTO Cities VALUES ('Gadžin Han', 101)
INSERT INTO Cities VALUES ('Doljevac', 101)
INSERT INTO Cities VALUES ('Merošina', 101)
INSERT INTO Cities VALUES ('Ražanj', 101)
INSERT INTO Cities VALUES ('Svrljig', 101)
INSERT INTO Cities VALUES ('Niš', 101)
INSERT INTO Cities VALUES ('Blace', 101)
INSERT INTO Cities VALUES ('Žitorađa', 101)
INSERT INTO Cities VALUES ('Kuršumlija', 101)
INSERT INTO Cities VALUES ('Prokuplje', 101)
INSERT INTO Cities VALUES ('Babušnica', 101)
INSERT INTO Cities VALUES ('Bela Palanka', 101)
INSERT INTO Cities VALUES ('Dimitrovgrad', 101)
INSERT INTO Cities VALUES ('Pirot', 101)
INSERT INTO Cities VALUES ('Bojnik', 101)
INSERT INTO Cities VALUES ('Vlasotice', 101)
INSERT INTO Cities VALUES ('Lebane', 101)
INSERT INTO Cities VALUES ('Leskovac', 101)
INSERT INTO Cities VALUES ('Medveđa', 101)
INSERT INTO Cities VALUES ('Crna Trava', 101)
INSERT INTO Cities VALUES ('Bosilegrad', 101)
INSERT INTO Cities VALUES ('Bujanovac', 101)
INSERT INTO Cities VALUES ('Vladičin Han', 101)
INSERT INTO Cities VALUES ('Vranje', 101)
INSERT INTO Cities VALUES ('Preševo', 101)
INSERT INTO Cities VALUES ('Surdulica', 101)
INSERT INTO Cities VALUES ('Trgovište', 101)
INSERT INTO Cities VALUES ('Golubovac', 101)
INSERT INTO Cities VALUES ('Kačanik', 101)
INSERT INTO Cities VALUES ('Kosovo Polje', 101)
INSERT INTO Cities VALUES ('Lipljan', 101)
INSERT INTO Cities VALUES ('Obilić', 101)
INSERT INTO Cities VALUES ('Podujevo', 101)
INSERT INTO Cities VALUES ('Uroševac', 101)
INSERT INTO Cities VALUES ('Štimlje', 101)
INSERT INTO Cities VALUES ('Štrpce', 101)
INSERT INTO Cities VALUES ('Priština', 101)
INSERT INTO Cities VALUES ('Dečani', 101)
INSERT INTO Cities VALUES ('Đakovica', 101)
INSERT INTO Cities VALUES ('Istok', 101)
INSERT INTO Cities VALUES ('Klina', 101)
INSERT INTO Cities VALUES ('Peć', 101)
INSERT INTO Cities VALUES ('Gora', 101)
INSERT INTO Cities VALUES ('Orahovac', 101)
INSERT INTO Cities VALUES ('Prizren', 101)
INSERT INTO Cities VALUES ('Suva Reka', 101)
INSERT INTO Cities VALUES ('Vučitrn', 101)
INSERT INTO Cities VALUES ('Zvečan', 101)
INSERT INTO Cities VALUES ('Zubin Potok', 101)
INSERT INTO Cities VALUES ('Kosovska Mitrovica', 101)
INSERT INTO Cities VALUES ('Leposavić', 101)
INSERT INTO Cities VALUES ('Srbica', 101)
INSERT INTO Cities VALUES ('Vitina', 101)
INSERT INTO Cities VALUES ('Gnjilane', 101)
INSERT INTO Cities VALUES ('Kosovska Kamenica', 101)
INSERT INTO Cities VALUES ('Novo Brdo', 101)
INSERT INTO Cities VALUES ('Beograd', 101)