// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("VillaManagement", SourceFile="Features\\VillaManagement.feature", SourceLine=0)]
    public partial class VillaManagementFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "VillaManagement.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "VillaManagement", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Create New Villa", SourceLine=2)]
        public virtual void CreateNewVilla()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create New Villa", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
 testRunner.Given("there was no villa with the name \"Test Villa\" linked with test villa owner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "Filed",
                            "Value"});
                table20.AddRow(new string[] {
                            "Name",
                            "Test Villa"});
                table20.AddRow(new string[] {
                            "PricePerDay",
                            "10.00"});
                table20.AddRow(new string[] {
                            "Address",
                            "Some Address 123"});
                table20.AddRow(new string[] {
                            "Longitude",
                            "0"});
                table20.AddRow(new string[] {
                            "Lattitude",
                            "0"});
                table20.AddRow(new string[] {
                            "PromoDescription",
                            "Test description"});
                table20.AddRow(new string[] {
                            "TermsOfUse",
                            "some terms"});
                table20.AddRow(new string[] {
                            "Capacitiy",
                            "5"});
                table20.AddRow(new string[] {
                            "NumberOfBeds",
                            "4"});
                table20.AddRow(new string[] {
                            "NumberOfRooms",
                            "2"});
#line 5
 testRunner.And("a new villa DTO was created with the following properties", ((string)(null)), table20, "And ");
#line hidden
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table21.AddRow(new string[] {
                            "HttpMethod",
                            "post"});
                table21.AddRow(new string[] {
                            "RelativeResourceUrl",
                            "/api/VillaManagement/CreateVilla"});
                table21.AddRow(new string[] {
                            "CookieUserId",
                            "2"});
                table21.AddRow(new string[] {
                            "CookieEmail",
                            "testvillaowner@gmail.com"});
#line 18
 testRunner.When("a request is sent to the API", ((string)(null)), table21, "When ");
#line hidden
#line 25
 testRunner.Then("a \"200\" status code should be received", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 26
 testRunner.And("a villa with the name \"Test Villa\" will be created and will be owned by \"testvill" +
                        "aowner@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Delete Existing Villa", SourceLine=27)]
        public virtual void DeleteExistingVilla()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete Existing Villa", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 28
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 29
 testRunner.Given("there was a villa in the database named \"Test Villa\" linked with villa owner with" +
                        " email \"testvillaowner@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 30
 testRunner.And("the villa with the name \"Test Villa\" that is linked with test villa owner had no " +
                        "reservations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 31
 testRunner.And("an id of the villa named \"Test Villa\" which is linked to the test owner is includ" +
                        "ed as path parameter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table22.AddRow(new string[] {
                            "HttpMethod",
                            "delete"});
                table22.AddRow(new string[] {
                            "RelativeResourceUrl",
                            "/api/VillaManagement/DeleteVilla"});
                table22.AddRow(new string[] {
                            "CookieEmail",
                            "testvillaowner@gmail.com"});
#line 33
 testRunner.When("a request is sent to the API", ((string)(null)), table22, "When ");
#line hidden
#line 39
 testRunner.Then("a \"200\" status code should be received", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 40
 testRunner.And("the villa with the name \"Test Villa\" will be deleted for the owner \"testvillaowne" +
                        "r@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Villa Update With existing Reservations", SourceLine=41)]
        public virtual void VillaUpdateWithExistingReservations()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Villa Update With existing Reservations", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 42
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 43
 testRunner.Given("there was a villa in the database named \"Test Villa\" linked with villa owner with" +
                        " email \"testvillaowner@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "Filed",
                            "Value"});
                table23.AddRow(new string[] {
                            "Name",
                            "Test Villa"});
                table23.AddRow(new string[] {
                            "PricePerDay",
                            "20.00"});
                table23.AddRow(new string[] {
                            "Address",
                            "Some Address 123"});
                table23.AddRow(new string[] {
                            "Longitude",
                            "0"});
                table23.AddRow(new string[] {
                            "Lattitude",
                            "0"});
                table23.AddRow(new string[] {
                            "PromoDescription",
                            "Test description"});
                table23.AddRow(new string[] {
                            "TermsOfUse",
                            "some changed terms"});
                table23.AddRow(new string[] {
                            "Capacitiy",
                            "5"});
                table23.AddRow(new string[] {
                            "NumberOfBeds",
                            "4"});
                table23.AddRow(new string[] {
                            "NumberOfRooms",
                            "2"});
#line 44
 testRunner.And("a new villa DTO was formed based on the villa from the database that is linked wi" +
                        "th test owner", ((string)(null)), table23, "And ");
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table24.AddRow(new string[] {
                            "HttpMethod",
                            "put"});
                table24.AddRow(new string[] {
                            "RelativeResourceUrl",
                            "/api/VillaManagement/UpdateVilla"});
#line 57
 testRunner.When("a request is sent to the API", ((string)(null)), table24, "When ");
#line hidden
#line 62
 testRunner.Then("a \"401\" status code should be received", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
