SET IDENTITY_INSERT Services ON;

INSERT INTO Services (ServiceId, OwnerId, ServiceType, Name, PricePerDay, CityId, Address, Longitude, Latitude, PromoDescription, TermsOfUse, AdditionalEquipment, AvailableFrom, AvailableTo, Capacity, IsPercentageTakenFromCanceledReservations, PercentageToTake) VALUES (0, 1, 0, 'Test villa', 19.50, 138, 'Test address 123', 20, 20, 'Awesome description for the villa', 'no terms', null, null, null, 10, 0, null)
 INSERT INTO AdditionalVillaServiceInfos VALUES (0, 10, 2)
INSERT INTO Services (ServiceId, OwnerId, ServiceType, Name, PricePerDay, CityId, Address, Longitude, Latitude, PromoDescription, TermsOfUse, AdditionalEquipment, AvailableFrom, AvailableTo, Capacity, IsPercentageTakenFromCanceledReservations, PercentageToTake)  VALUES (1, 3, 2, 'Sunset champagne cornflower experience', 19.50, 138, 'Bulevar despota Stefana 7', 19.8227, 45.2396, 'Unforgettable sunset fishing among the Serbian fields, where the grass is always green and the people are always chill.', 'Absolutely everithing is allowed, except drugs. Do not bring drugs.', 'Fishing stick:5;Beer:10;', null, null, 10, 0, null)
 INSERT INTO AdditionalAdventureInfos VALUES (1, 'You can use our speakers for music, drink our beer, eat our food. Also, your wish is our command. Seriously, anything you need we will supply. There is a local market nearby, our guests usually love it! Just stop by, and you will become our regular customer. Cheers!')
 INSERT INTO Services (ServiceId, OwnerId, ServiceType, Name, PricePerDay, CityId, Address, Longitude, Latitude, PromoDescription, TermsOfUse, AdditionalEquipment, AvailableFrom, AvailableTo, Capacity, IsPercentageTakenFromCanceledReservations, PercentageToTake) VALUES (2, 6, 1, 'Test boat', 19.50, 161, 'Test address 888', 20, 20, 'Awesome description for the boat', 'no terms', null, null, null, 10, 0, null)
 INSERT INTO AdditionalBoatServiceInfos VALUES (2, 20, 0, 5, 80, 95)

SET IDENTITY_INSERT Services OFF;