INSERT INTO SystemConfigurations VALUES ('MailAddress', 'zamisr.isa@gmail.com')
INSERT INTO SystemConfigurations VALUES ('MailPassword', 'isamail123')
INSERT INTO SystemConfigurations VALUES ('MailPort', '587')
INSERT INTO SystemConfigurations VALUES ('MailHost', 'smtp.gmail.com')
INSERT INTO SystemConfigurations VALUES ('MaxImageSize', '1000000')
INSERT INTO SystemConfigurations VALUES ('BusinessInfoBackPeriod', '10')